apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: pvc-grafana # Sets PVC's name
  namespace: monitoring
  labels:
    name: grafana-deployment # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi # Sets PVC's size
