apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: kubernetes-grafana
deploy:
  kubectl:
    manifests:
    - 00-namespace.yaml
    - 01-grafana-datasource-config.yaml
    - 02-grafana-pv.yaml
    - 03-grafana-pvc.yaml
    - 04-grafana-deployment.yaml
    - 05-grafa-service.yaml
