apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: pv-grafana # Sets PV name
  namespace: monitoring
  labels:
    type: local # Sets PV's type
    app: grafana-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/grafana # Sets PV's host path
