apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-storage
  namespace: monitoring-grafana
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: none
